### ISSUE TITLE
why doesnt zutty support transparent backgrounds?

### ISSUE THREAD

**Issue by darkralts** [tomscii/zutty#108]
i read the faq, is there a specific reason as to why you wont add them?

**Comment by tomscii** [comment]
Transparent backgrounds are an anti-feature, they make the text in the terminal less legible.
Life is too short to spend it on distracting mistakes like that (already true for *using* such a setup, doubly so for *implementing* it in a terminal emulator).

**Comment by clort81** [comment]
> Transparent backgrounds are an anti-feature, they make the text in the terminal less legible. Life is too short to spend it on distracting mistakes like that (already true for _using_ such a setup, doubly so for _implementing_ it in a terminal emulator).


I have solved the problem by writing shaders that keep foreground text opaque while allowing background to show through.  A dark background with a bright foreground text looks quite nice and readable.  
![pixom_keycolor_transparency_example](https://user-images.githubusercontent.com/51511737/227165298-a58ce034-e8ff-4924-89d1-d31f019eb877.png)

Zutty does not need to implement transparency - the window-manager (window compositor) has this job.

This works fine with zutty as-is.

**Comment by darkralts** [comment]
> Transparent backgrounds are an anti-feature, they make the text in the terminal less legible.
> Life is too short to spend it on distracting mistakes like that (already true for using such a setup, doubly so for implementing it in a terminal emulator).

so basically the classic "i do not like this feature therefore i will not add it"

i mean fair, its your own program do what you want :) 

definitely not an anti-feature though and more a personal preference thing.

Also thats a pretty cool workaround @clort81 

i think writing shaders from scratch might be a bit outside most users scope though,

**Comment by tomscii** [comment]
@darkralts Thank you for your valued response, it is most appreciated.

However, let's get a few things straight though.

1. I write a program in my free time and without compensation from anyone, extensively document it complete with my goals and intentions (see, there is even a FAQ!) also in my free time and without compensation from anyone, and publish it on the internet for anyone who finds it useful or interesting.
2. What is and what is not a feature/anti-feature in this program, I get to decide (see point 1 above). Period. Don't agree with me? Fine, submit a patch. Better, write your own.
3. I have expressly NOT asked or endorsed anyone to use my program (it's even in the FAQ)! You chose to do so at your own volition, and I have nothing in my interest to keep it that way.
4. So you just can't accept that feature X is missing. Well, the reason is in the FAQ. See also point 2 above. But you open... an issue.
5. I should have just closed the issue without even bothering to comment or should have, at most, pasted in the link to the FAQ (that you have already seen), but I, aiming to practice patience in the face of ignorance and donating EVEN MORE OF MY TIME AND MY LIFE, wrote an actual answer to your NON-issue question.
6. Things should have well ended there for anyone with a modicum of common sense, but YOU chose to take it up a notch and are now criticizing my work in the most disrespective manner:

> so basically the classic "i do not like this feature therefore i will not add it"

I have outlined reasons that you chose to disregard (and of course there are several other technical reasons you, self-entitled user, are not expected to know anything about), instead you claim something that I have never said or implied. That is intellectually dishonest. More so, it is utterly insulting. I expect your due apologies.

**Comment by darkralts** [comment]
lol
