### ISSUE TITLE
[Feature request] Allow double width fonts with a different (smaller) font size than the main one

### ISSUE THREAD

**Issue by neeshy** [tomscii/zutty#123]
In my case, I'd like to use Terminus at size 20px and Unifont (which only provides a 16px size). Without manually modifying the font file to extend each glyph's bounding box to 10x20 (or 20x20 for double width glyphs), this setup isn't currently possible on zutty.

**Comment by tomscii** [comment]
This is not supported because it does not make sense. Either resizing the glyphs or leaving spaces around them is an inferior solution and will inevitably cause user complaints, which means there would not be a net improvement after adding a bunch of complexity.

There are matching fonts without such a problem; people should stick to such combinations (as documented).
