### ISSUE TITLE
Character width doubled with D2Coding font

### ISSUE THREAD

**Issue by yoohaemin** [tomscii/zutty#91]
Hi, I'm trying to use the d2coding font with zutty: https://github.com/naver/d2codingfont
I downloaded the zip file with version 1.3.2, unpacked it, renamed it so that zutty can find it, and ran like this:
`zutty -font D2Coding -fontpath ~/Downloads/D2Coding`

It looks like zutty picks the font up, but every character looks double width. Maybe it has something to do with the fact that the font contains double width chars? (hangul)

Anyways, would appreciate if you could look into it. Please let me know if you need more details.

![Screenshot zutty](https://user-images.githubusercontent.com/22650536/193868642-fa0fe9cf-b227-4da9-81d5-773134b42fcb.png)

**Comment by tomszilagyi** [comment]
This is a regularly re-surfacing issue with variable width fonts, see #37, #67, #69.

I'm sure there is room for improvement in decoding certain fonts, but personally all the fonts I've ever wanted to use work perfectly well with Zutty, and the issue seems trickier than a trivial, easy fix within Zutty.

If you feel sufficiently motivated to contribute, I suggest looking at my last comment on #67 and take it from there. Feel free to ask questions if you get stuck.

**Comment by tomscii** [comment]
Added a [FAQ entry](https://github.com/tomscii/zutty/wiki/FAQ#q-font-xyz-does-not-load-in-zutty-or-looks-crappy-what-should-i-do)
